### PR TITLE
Fix read-only command whitelist & add recursive mode

### PR DESCRIPTION
**Pull request by twilligon**
It appears your `--read-only` mode is actually a `--write-only` mode! As I mentioned in the first commit message:

> As git-shell-enforce-directory will run on the remote, git-receive-pack will be
> run on *write* operations, not read operations. git-upload-pack is actually
> called when the *client* calls 'git fetch', 'git pull', etc.

This first commit is the most important. I also allowed multiple repository paths (if any of them match, the command is allowed). Additionally, I added a `--recursive` option: when enabled, any repo in a subdirectory of the given paths will be whitelisted.

### CODE REVIEW

**Comment by simmel** [comment]
Hey! Thank for the PR!
I somehow unwatched my own repo hence the late reply!

I’m gonna check out the changes but I’m on parental leave so neither my brain nor my time is really here so please be patient :)

**Comment by twilligon** [comment]
I'm not sure about that. [clap docs](https://docs.rs/clap/2.32.0/clap/struct.Arg.html#method.hidden) only seems to mention hiding an argument's *help text* from the user, not disabling parsing. I think you could work around this (and still parse with clap) by making it a non-positional, hidden, required argument which [takes a value](https://docs.rs/clap/2.32.0/clap/struct.Arg.html#method.takes_value), but that's a little weird.

**Comment by simmel** [comment]
Heh, I see what you mean now with clap, environment variables and indexes. Truly a mess.

I'm working on pulling in your patches plus adding some tests and refactoring. At least now my laptop is working as it should, now I just need to take the time = )

**Comment by simmel** [comment]
Oh man, github resolves things automatically now when it's merged (well, rebased)?

Anyway, I've merged your commits but I'm gonna add some tests and move some things to functions.

Thanks for the pull request!

**Pull request merged**
